esphome:
  name: project-template
  friendly_name: Project Template
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: arduino

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome

# Add Improv Serial component
improv_serial:

wifi:
  # Placeholder credentials (not used, but required for validation)
  ssid: "your_wifi"
  password: "your_password"
  ap:
    ssid: "Fallback_AP"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:
