name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build lilygoT-Display-QuadSensor / ESPHome stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6.0.2
      - name: Dummy secrets for CI
        run: cp secrets.yaml.example secrets.yaml
      - name: ESPHome compile (factory includes core)
        uses: esphome/build-action@v7.2.0
        with:
          yaml-file: lilygoT-Display-QuadSensor.factory.yaml
          version: stable
